import type { TradeRecord } from "@/lib/types";

export const demoTrades: TradeRecord[] = [
  {
    id: "demo-1",
    userId: "demo-user",
    date: "2026-04-01",
    time: "09:35",
    market: "Stocks",
    instrument: "SPY",
    setup: "Opening Drive",
    direction: "Long",
    entryPrice: 519.15,
    exitPrice: 522.4,
    stopLoss: 517.9,
    takeProfit: 523.5,
    size: 300,
    fees: 18.5,
    resultUsd: 956.5,
    resultPercent: 1.84,
    notes: "Clean trend continuation after reclaiming VWAP. Added on first pullback.",
    followedPlan: true,
    revengeTrade: false,
    fomo: false,
    overtrading: false,
    respectStopLoss: true,
    preEmotion: "Calm and focused.",
    duringEmotion: "Confident after first target hit.",
    postEmotion: "Satisfied. Good patience.",
    mistake: "Could have scaled a little slower.",
    lesson: "When trend and breadth align, hold core longer.",
    disciplineScore: 9,
    setupTags: ["trend", "opening", "a-plus"],
    screenshotUrl: "https://images.unsplash.com/photo-1642790291298-d15ff82d13a0?auto=format&fit=crop&w=1200&q=80",
    createdAt: "2026-04-01T09:50:00.000Z"
  },
  {
    id: "demo-2",
    userId: "demo-user",
    date: "2026-04-02",
    time: "11:12",
    market: "Futures",
    instrument: "NQ",
    setup: "Liquidity Sweep",
    direction: "Short",
    entryPrice: 18742.5,
    exitPrice: 18696.75,
    stopLoss: 18766.5,
    takeProfit: 18690,
    size: 2,
    fees: 8.4,
    resultUsd: 174.1,
    resultPercent: 0.93,
    notes: "Fade after failed breakout into prior high.",
    followedPlan: true,
    revengeTrade: false,
    fomo: false,
    overtrading: false,
    respectStopLoss: true,
    preEmotion: "Neutral.",
    duringEmotion: "A bit rushed on entry.",
    postEmotion: "Good acceptance.",
    mistake: "Entry was slightly early.",
    lesson: "Wait for displacement candle after sweep.",
    disciplineScore: 8,
    setupTags: ["liquidity", "reversal"],
    screenshotUrl: null,
    createdAt: "2026-04-02T11:24:00.000Z"
  },
  {
    id: "demo-3",
    userId: "demo-user",
    date: "2026-04-03",
    time: "10:06",
    market: "Crypto",
    instrument: "BTCUSD",
    setup: "Breakout Retest",
    direction: "Long",
    entryPrice: 71280,
    exitPrice: 70920,
    stopLoss: 70890,
    takeProfit: 71840,
    size: 0.4,
    fees: 21.8,
    resultUsd: -165.8,
    resultPercent: -0.51,
    notes: "Retest failed and momentum faded quickly.",
    followedPlan: false,
    revengeTrade: false,
    fomo: true,
    overtrading: false,
    respectStopLoss: true,
    preEmotion: "Wanted to catch momentum.",
    duringEmotion: "Some hesitation when candle reversed.",
    postEmotion: "Slight frustration but controlled.",
    mistake: "Entered before reclaim confirmation.",
    lesson: "Do not anticipate crypto range breaks.",
    disciplineScore: 6,
    setupTags: ["breakout", "crypto"],
    screenshotUrl: null,
    createdAt: "2026-04-03T10:18:00.000Z"
  },
  {
    id: "demo-4",
    userId: "demo-user",
    date: "2026-04-04",
    time: "13:42",
    market: "Options",
    instrument: "AAPL 190C",
    setup: "Sniper Pullback",
    direction: "Long",
    entryPrice: 4.15,
    exitPrice: 5.48,
    stopLoss: 3.8,
    takeProfit: 5.7,
    size: 8,
    fees: 12.2,
    resultUsd: 1051.8,
    resultPercent: 32.05,
    notes: "Strong afternoon continuation after earnings gap hold.",
    followedPlan: true,
    revengeTrade: false,
    fomo: false,
    overtrading: false,
    respectStopLoss: true,
    preEmotion: "Locked in.",
    duringEmotion: "Patient and deliberate.",
    postEmotion: "High confidence without euphoria.",
    mistake: "No major issue.",
    lesson: "Afternoon trend days can still offer A+ entries.",
    disciplineScore: 10,
    setupTags: ["pullback", "options", "trend-day"],
    screenshotUrl: null,
    createdAt: "2026-04-04T14:04:00.000Z"
  },
  {
    id: "demo-5",
    userId: "demo-user",
    date: "2026-04-07",
    time: "09:58",
    market: "Forex",
    instrument: "EURUSD",
    setup: "London Reversal",
    direction: "Short",
    entryPrice: 1.0874,
    exitPrice: 1.0892,
    stopLoss: 1.0894,
    takeProfit: 1.0838,
    size: 100000,
    fees: 6.5,
    resultUsd: -186.5,
    resultPercent: -0.17,
    notes: "Shorted into support and got squeezed.",
    followedPlan: false,
    revengeTrade: true,
    fomo: false,
    overtrading: true,
    respectStopLoss: true,
    preEmotion: "Impatient after missed first move.",
    duringEmotion: "Wanted the trade to work too quickly.",
    postEmotion: "Disappointed. Clear revenge energy.",
    mistake: "Forced a second trade outside session plan.",
    lesson: "After missing A setup, reduce size or stay flat.",
    disciplineScore: 4,
    setupTags: ["forex", "session", "reversal"],
    screenshotUrl: null,
    createdAt: "2026-04-07T10:08:00.000Z"
  },
  {
    id: "demo-6",
    userId: "demo-user",
    date: "2026-04-08",
    time: "12:25",
    market: "Stocks",
    instrument: "NVDA",
    setup: "Breakout",
    direction: "Long",
    entryPrice: 914.2,
    exitPrice: 922.9,
    stopLoss: 909.8,
    takeProfit: 925.6,
    size: 75,
    fees: 14.6,
    resultUsd: 637.9,
    resultPercent: 0.95,
    notes: "Strong relative strength, held through midday coil.",
    followedPlan: true,
    revengeTrade: false,
    fomo: false,
    overtrading: false,
    respectStopLoss: true,
    preEmotion: "Patient.",
    duringEmotion: "Steady confidence.",
    postEmotion: "Professional execution.",
    mistake: "Could have left a runner.",
    lesson: "When sector leaders consolidate above VWAP, give them room.",
    disciplineScore: 8,
    setupTags: ["momentum", "breakout"],
    screenshotUrl: null,
    createdAt: "2026-04-08T12:46:00.000Z"
  },
  {
    id: "demo-7",
    userId: "demo-user",
    date: "2026-04-09",
    time: "14:10",
    market: "Futures",
    instrument: "ES",
    setup: "VWAP Reclaim",
    direction: "Long",
    entryPrice: 5328.25,
    exitPrice: 5337.75,
    stopLoss: 5323.5,
    takeProfit: 5340.5,
    size: 3,
    fees: 9.8,
    resultUsd: 1415.2,
    resultPercent: 0.78,
    notes: "Great reclaim into power hour expansion.",
    followedPlan: true,
    revengeTrade: false,
    fomo: false,
    overtrading: false,
    respectStopLoss: true,
    preEmotion: "Composed.",
    duringEmotion: "Locked in.",
    postEmotion: "Excellent execution.",
    mistake: "No issue.",
    lesson: "Power hour reclaims deserve full focus.",
    disciplineScore: 9,
    setupTags: ["vwap", "futures"],
    screenshotUrl: null,
    createdAt: "2026-04-09T14:26:00.000Z"
  },
  {
    id: "demo-8",
    userId: "demo-user",
    date: "2026-04-10",
    time: "10:31",
    market: "Stocks",
    instrument: "TSLA",
    setup: "Opening Fade",
    direction: "Short",
    entryPrice: 172.3,
    exitPrice: 175.15,
    stopLoss: 175.2,
    takeProfit: 168.4,
    size: 180,
    fees: 16.3,
    resultUsd: -529.3,
    resultPercent: -1.66,
    notes: "Ignored strength in QQQ and kept holding the fade.",
    followedPlan: false,
    revengeTrade: false,
    fomo: false,
    overtrading: false,
    respectStopLoss: false,
    preEmotion: "Confident but biased.",
    duringEmotion: "Stubbornness showed up.",
    postEmotion: "Clear reminder to respect invalidation.",
    mistake: "Moved stop after entry.",
    lesson: "Bias is expensive. Accept when tape disagrees.",
    disciplineScore: 3,
    setupTags: ["fade", "open"],
    screenshotUrl: null,
    createdAt: "2026-04-10T10:48:00.000Z"
  }
];
